

public_data.customer_address
public_data
.customer_demographics
public_data.date_dim
public_data.warehouse
public_data.ship_mode
public_data.time_dim
public_data.reason
public_data.income_band
public_data.item
public_data.store
public_data.call_center
public_data.customer
public_data.web_site
public_data.store_returns
public_data.household_demographics
public_data.web_page
public_data.promotion
public_data.catalog_page
public_data.inventory
public_data.catalog_returns
public_data.web_returns
public_data.web_sales
public_data.catalog_sales
public_data.store_sales